[package]
name = "aoclib"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "aoc-2022"
path = "src/main.rs"

[features]
wasm = ["dep:wasm-bindgen"]

[dependencies]
wasm-bindgen = { version = "0.2.63", optional = true }
regex = "1"
pathfinding = "4.0.0"
